# Part 7 - sorting data

In [1]:
import pandas as pd

In [2]:
survey_df = pd.read_csv('data/survey_results_public.csv')
schema_df = pd.read_csv('data/survey_results_schema.csv')

In [3]:
people_df = pd.DataFrame({
    'first': 'Corey Jane John'.split(),
    'last': 'Schafer Doe Doe'.split(),
    'email': 'CoreyMSchafer@gmail.com JaneDoe@gmail.com JohnDoe@gmail.com'.split()
})
people_df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [4]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [5]:
people_df.sort_values(
    by='last',
    ascending=False
)

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
2   John      Doe        JohnDoe@gmail.com

In [6]:
people_df.sort_values(
    by=['last', 'first'],
    ascending=[True, False]
)

   first     last                    email
2   John      Doe        JohnDoe@gmail.com
1   Jane      Doe        JaneDoe@gmail.com
0  Corey  Schafer  CoreyMSchafer@gmail.com