In [1]:
import pandas as pd
import random

In [2]:
NAME_LIST = 'bob mark joe chris'.split()
SURNAME_LIST = 'smith brown doe iggins'.split()
ROW_COUNT = 10

In [3]:
names = (random.choice(NAME_LIST) for _ in range(ROW_COUNT))
surnames = (random.choice(SURNAME_LIST) for _ in range(ROW_COUNT))
data = ((name, surname, f'{name}.{surname}@mail.com') for name, surname in zip(names, surnames))
records = [{'first': first, 'last': last, 'email':email} for first, last, email in data]
df = pd.DataFrame(records); df

   first    last                 email
0    bob   smith    bob.smith@mail.com
1  chris   smith  chris.smith@mail.com
2    bob   brown    bob.brown@mail.com
3    joe     doe      joe.doe@mail.com
4    bob  iggins   bob.iggins@mail.com
5    joe   brown    joe.brown@mail.com
6    joe   smith    joe.smith@mail.com
7   mark  iggins  mark.iggins@mail.com
8  chris     doe    chris.doe@mail.com
9  chris     doe    chris.doe@mail.com

In [4]:
df.drop(0)

   first    last                 email
1  chris   smith  chris.smith@mail.com
2    bob   brown    bob.brown@mail.com
3    joe     doe      joe.doe@mail.com
4    bob  iggins   bob.iggins@mail.com
5    joe   brown    joe.brown@mail.com
6    joe   smith    joe.smith@mail.com
7   mark  iggins  mark.iggins@mail.com
8  chris     doe    chris.doe@mail.com
9  chris     doe    chris.doe@mail.com

In [5]:
df.drop(columns='first')

     last                 email
0   smith    bob.smith@mail.com
1   smith  chris.smith@mail.com
2   brown    bob.brown@mail.com
3     doe      joe.doe@mail.com
4  iggins   bob.iggins@mail.com
5   brown    joe.brown@mail.com
6   smith    joe.smith@mail.com
7  iggins  mark.iggins@mail.com
8     doe    chris.doe@mail.com
9     doe    chris.doe@mail.com

In [6]:
df.drop(index=[n for n in range(df.shape[0]) if n % 2])

   first    last                email
0    bob   smith   bob.smith@mail.com
2    bob   brown   bob.brown@mail.com
4    bob  iggins  bob.iggins@mail.com
6    joe   smith   joe.smith@mail.com
8  chris     doe   chris.doe@mail.com

In [7]:
df.drop(index=[n for n in range(df.shape[0]) if random.choice([True, False])])

  first    last                 email
3   joe     doe      joe.doe@mail.com
5   joe   brown    joe.brown@mail.com
6   joe   smith    joe.smith@mail.com
7  mark  iggins  mark.iggins@mail.com

In [8]:
df.drop(columns=df.columns[0])

     last                 email
0   smith    bob.smith@mail.com
1   smith  chris.smith@mail.com
2   brown    bob.brown@mail.com
3     doe      joe.doe@mail.com
4  iggins   bob.iggins@mail.com
5   brown    joe.brown@mail.com
6   smith    joe.smith@mail.com
7  iggins  mark.iggins@mail.com
8     doe    chris.doe@mail.com
9     doe    chris.doe@mail.com

In [9]:
filt = (df['email'].str.contains('smith'))
df[filt].index

Index([0, 1, 6], dtype='int64')